---

- name: Install requirements
  apt: pkg={{item}}
  with_items:
      - postfix
      - ca-certificates
      - mailutils

- name: Ensure /etc/postfix directory is owned by postfix user
  file: path=/etc/postfix owner=postfix
  notify: postfix restart